# Generated by Django 3.1.4 on 2021-01-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resolved_answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comment'),
        ),
    ]
