# Generated by Django 3.1.4 on 2021-02-07 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='AnswerRating',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='question',
            name='resolved_answer_id',
        ),
        migrations.AddField(
            model_name='question',
            name='resolved_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.answer'),
        ),
    ]
